name: hello world
on:
  push:
    paths:
      - index.html
    branches:
      - main
jobs:
  # print:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: print hello world
  #     run: echo "hello, world"

  notify:
     runs-on: ubuntu-latest
     steps:
     - name: notify change
       run: echo "hello, world"
    
    
